package rules;

import java.util.Set;
import java.util.HashSet;
import POHandling.models.ProductOrder;

global Set<String> workingDays;
global Set<String> holidays;

rule "Working Day Rule"
when
    $order: ProductOrder(orderDate not in (workingDays) || orderDate in (holidays))
then
    System.out.println("Rule triggered!");
     // Set it to the date of the next working day
     java.util.Calendar cal = java.util.Calendar.getInstance();
     cal.setTime($order.getOrderDate());
     do {
          cal.add(java.util.Calendar.DAY_OF_MONTH, 1);
      } while (!workingDays.contains(cal.getDisplayName(java.util.Calendar.DAY_OF_WEEK, java.util.Calendar.LONG, java.util.Locale.US)) || holidays.contains(cal.getTime()));
      $order.setOrderProcessDate(cal.getTime());
end
